_BASE_: YTVIS2019.yaml
DATASETS:
  DATASET_RATIO: [1.0, 0.8]
  TRAIN: ("coco2ytvis2021_train", "ytvis_2021_train")
  TEST: ("ytvis_2021_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (6000, 12000)
  MAX_ITER: 16000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 1000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  SAMPLING_FRAME_RANGE: 20
  SAMPLING_FRAME_NUM: 10
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: [ ]
  MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 480
  CROP:
    ENABLED: True
    CLIP_FRAME_CNT: 10
    TYPE: "absolute_range"
    SIZE: (384, 600)
  PSEUDO:
    AUGMENTATIONS: [ 'rotation' ]
    MIN_SIZE_TRAIN: (320, 352, 392, 416, 448, 480, 512, 544, 576, 608, 640)
    MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: True
      TYPE: "absolute_range"
      SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 2000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8
VERSION: 2
